#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp)
cat > $payload <&0
BUILD=$(jq -r '.version.build // ""' < $payload)
API=$(jq -r '.source.api // ""' < $payload)
TEAM=$(jq -r '.source.team // ""' < $payload)
PIPELINE=$(jq -r '.source.pipeline // ""' < $payload)
JOB="$(jq -r '(.source.job // "")' < $payload)"

URI_JOB=`echo $JOB | jq -sRr @uri | sed 's/%0A//g'`
URL=$API/teams/$TEAM/pipelines/$PIPELINE/jobs/$URI_JOB/builds/$BUILD
meta=`jq -n "[]" | jq ". + [
  {name: \"pipeline\", value: \"${PIPELINE}\"},
  {name: \"job\", value: \"${JOB}\"},
  {name: \"url\", value: \"${URL}\"}
]"`

jq -n "{
  version: {ref: $(echo $BUILD | jq -R .)},
  metadata: $meta
}" >&3
